### PR TITLE
Pimlinders patch 1

### PR DESCRIPTION
**Pull request by pimlinders**
@mitchthorson fix for hero image? Use hero_image in story.yml

### CODE REVIEW

**Comment by pimlinders** [comment]
This seems to only fix it for dev. Once build is create it resorts back to test.gif.

**Comment by pimlinders** [comment]
Any way to populate this based on graphics_config?

**Comment by mitchthorson** [comment]
i feel like this should fix it, I'll merge and if it's still happening I'll investigate further...that was leftover from some old code but i forgot to strip it out.

**Comment by pimlinders** [comment]
@mitchthorson seemed like during a production build it would loose its background if it wasn't populated. Dev worked fine either way.

**Comment by mitchthorson** [comment]
ah probably has to do with production URL replacement. one more thing we can discuss in team meeting later this week. production build swaps out absolute urls, so if assets aren't deployed/synced yet, they'll get lost locally.

**Pull request merged**
